AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/playground.rb'
    - 'vagrant/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'scripts/**/*'
    - 'lib/generators/**/*'
    - 'node_modules/**/*'
    - 'test/dummy/db/**/*'
    - 'test/dummy/config/**/*'
    - 'lib/super_hash.rb'

Metrics:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EndAlignment:
  AutoCorrect: true

Layout/LineLength:
  Enabled: false
