POST https://a520e575.ngrok.io/nuntius/callbacks/d7836f0c-10de-47bb-aaaa-2407873aecbe
Content-Type: application/json

{"Called":"+31641085630","ToState":"","CallerCountry":"US","Direction":"outbound-api","CallerState":"CA","ToZip":"","CallSid":"CAffe5a23e923aea2d405d97c9c0a7b501","To":"+31641085630","CallerZip":"94105","ToCountry":"NL","ApiVersion":"2010-04-01","CalledZip":"","CalledCity":"","CallStatus":"in-progress","From":"+14153736696","AccountSid":"AC92bf1782ac7790aa62d13f2135a887aa","CalledCountry":"NL","CallerCity":"SAN FRANCISCO","Caller":"+14153736696","FromCountry":"US","ToCity":"","FromCity":"SAN FRANCISCO","CalledState":"","FromZip":"94105","FromState":"CA","message_id":"d7836f0c-10de-47bb-aaaa-2407873aecbe"}

###

POST https://vorto.dev/nuntius/api/events
Authorization: Basic dfe6296d272e46978df6c90622e3ba78 -
Content-Type: application/json

{
    "scope": "wms",
    "event": "shipped",
    "locale": "en",
    "context": {
        "to": "tom@boxture.com",
        "customer_ref": "SBL1234567",
        "consignee_name": "Sander Helsloot",
        "name": "Foo",
        "moo": "Cow"
    },
    "attachments": [{
        "url": ""
    }]
}

###

POST https://9f71-85-144-159-189.eu.ngrok.io/messaging/feedback/awssns
Content-Type: application/json

{
       "notificationType":"Bounce",
       "bounce":{
          "bounceType":"Permanent",
          "reportingMTA":"dns; email.example.com",
          "bouncedRecipients":[
             {
                "emailAddress":"jane@example.com",
                "status":"5.1.1",
                "action":"failed",
                "diagnosticCode":"smtp; 550 5.1.1 <jane@example.com>... User"
             }
          ],
          "bounceSubType":"General",
          "timestamp":"2016-01-27T14:59:38.237Z",
          "feedbackId":"00000138111222aa-33322211-cccc-cccc-cccc-ddddaaaa068a-000000",
          "remoteMtaIp":"127.0.2.0"
       },
       "mail":{
          "timestamp":"2016-01-27T14:59:38.237Z",
          "source":"john@example.com",
          "sourceArn": "arn:aws:ses:us-east-1:888888888888:identity/example.com",
          "sourceIp": "127.0.3.0",
          "sendingAccountId":"123456789012",
          "callerIdentity": "IAM_user_or_role_name",
          "messageId":"00000138111222aa-33322211-cccc-cccc-cccc-ddddaaaa0680-000000",
          "destination":[
            "jane@example.com",
            "mary@example.com",
            "richard@example.com"],
          "headersTruncated":false,
          "headers":[
           {
             "name":"From",
             "value":"\"John Doe\" <john@example.com>"
           },
           {
             "name":"To",
             "value":"\"Jane Doe\" <jane@example.com>, \"Mary Doe\" <mary@example.com>, \"Richard Doe\" <richard@example.com>"
           },
           {
             "name":"Message-ID",
             "value":"custom-message-ID"
           },
           {
             "name":"Subject",
             "value":"Hello"
           },
           {
             "name":"Content-Type",
             "value":"text/plain; charset=\"UTF-8\""
           },
           {
             "name":"Content-Transfer-Encoding",
             "value":"base64"
           },
           {
             "name":"Date",
             "value":"Wed, 27 Jan 2016 14:05:45 +0000"
           }
          ],
          "commonHeaders":{
             "from":[
                "John Doe <john@example.com>"
             ],
             "date":"Wed, 27 Jan 2016 14:05:45 +0000",
             "to":[
                "Jane Doe <jane@example.com>, Mary Doe <mary@example.com>, Richard Doe <richard@example.com>"
             ],
             "messageId":"custom-message-ID",
             "subject":"Hello"
           }
        }
    }
